### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by robphoenix** [robphoenix/trawl#1]
I don't know why, yet.

```
C:\Users\robertph\go\src\github.com\robphoenix\trawl [master ↓]
λ  .\trawl.exe
panic: runtime error: index out of range

goroutine 33 [running]:
panic(0x5f6600, 0xc042004040)
        C:/Go/src/runtime/panic.go:500 +0x1af
main.New(0x27, 0x500, 0xc04208c990, 0x2d, 0xc04203eee0, 0x8, 0x8, 0x18, 0x0, 0x0, ...)
        C:/Users/robertph/go/src/github.com/robphoenix/trawl/main.go:88 +0x3a8
main.main.func1(0xc04203c300, 0x27, 0x500, 0xc04208c990, 0x2d, 0xc04203eee0, 0x8, 0x8, 0x18)
        C:/Users/robertph/go/src/github.com/robphoenix/trawl/main.go:50 +0x56
created by main.main
        C:/Users/robertph/go/src/github.com/robphoenix/trawl/main.go:55 +0x154
C:\Users\robertph\go\src\github.com\robphoenix\trawl [master ↓]
λ  .\trawl.exe
panic: runtime error: index out of range

goroutine 29 [running]:
panic(0x5f6600, 0xc042004040)
        C:/Go/src/runtime/panic.go:500 +0x1af
main.New(0x25, 0x500, 0xc0420c4c40, 0x13, 0xc04203eec0, 0x8, 0x8, 0x18, 0x0, 0x0, ...)
        C:/Users/robertph/go/src/github.com/robphoenix/trawl/main.go:88 +0x3a8
main.main.func1(0xc04203c300, 0x25, 0x500, 0xc0420c4c40, 0x13, 0xc04203eec0, 0x8, 0x8, 0x18)
        C:/Users/robertph/go/src/github.com/robphoenix/trawl/main.go:50 +0x56
created by main.main
        C:/Users/robertph/go/src/github.com/robphoenix/trawl/main.go:55 +0x154
panic: runtime error: index out of range

goroutine 34 [running]:
panic(0x5f6600, 0xc042004040)
        C:/Go/src/runtime/panic.go:500 +0x1af
main.New(0x26, 0x500, 0xc04208c9c0, 0x2d, 0xc04203eee8, 0x8, 0x8, 0x18, 0x0, 0x0, ...)
        C:/Users/robertph/go/src/github.com/robphoenix/trawl/main.go:88 +0x3a8
main.main.func1(0xc04203c300, 0x26, 0x500, 0xc04208c9c0, 0x2d, 0xc04203eee8, 0x8, 0x8, 0x18)
        C:/Users/robertph/go/src/github.com/robphoenix/trawl/main.go:50 +0x56
created by main.main
        C:/Users/robertph/go/src/github.com/robphoenix/trawl/main.go:55 +0x154
```

**Comment by robphoenix** [comment]
Does now. It was because of all the `media disconnected` interfaces returning empty arrays that were being looped over to extract the ipv4 address and so panicking as out of range.
